name: Latest GCC

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 3 * *"

jobs:
  on64bit:
    runs-on: ubuntu-22.04
    steps:
      - 
        name: Git Checkout
        uses: actions/checkout@v4
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push on linux/amd64
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: false
          build-args: IMAGE_BASE=gcc
      -
        name: Build and push on linux/arm/v7
        uses: docker/build-push-action@v5
        continue-on-error: true
        with:
          platforms: linux/arm/64
          push: false
          build-args: IMAGE_BASE=gcc

  armv5-7:
    runs-on: ubuntu-22.04
    steps:
      - 
        name: Git Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push on linux/arm/v5
        uses: docker/build-push-action@v5
        continue-on-error: true
        with:
          platforms: linux/arm/v5
          push: false
          build-args: IMAGE_BASE=gcc
      -
        name: Build and push on linux/arm/v7
        uses: docker/build-push-action@v5
        continue-on-error: true
        with:
          platforms: linux/arm/v7
          build-args: IMAGE_BASE=gcc
          push: false

  others:
    runs-on: ubuntu-22.04
    steps:
      - 
        name: Git Checkout
        uses: actions/checkout@v4
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push on linux/mips64le
        uses: docker/build-push-action@v5
        continue-on-error: true
        with:
          platforms: linux/s390x
          push: false
          build-args: IMAGE_BASE=gcc
      -
        name: Build and push on linux/ppc64le
        uses: docker/build-push-action@v5
        continue-on-error: true
        with:
          platforms: linux/ppc64le
          push: false
          build-args: IMAGE_BASE=gcc