name: IRC notifications

on: [push, pull_request, create, issues]

jobs:
  notification:
    runs-on: ubuntu-22.04
    name: IRC Notification
    steps:
    - name: Skip if not aircrack-ng/aircrack-ng
      run: |
        if [ "${{ github.repository }}" != 'aircrack-ng/aircrack-ng' ]; then
          exit 1
        fi
    # If 2 consecutive calls happen, the second one can fail as
    #  it's not able to get the username requested
    - name: Generate random username
      id: random
      run: |
        USERNAME=$(mktemp -u | awk -F. '{print "gh-a-ng-" $2}')
        echo "username=${USERNAME}" >> $GITHUB_OUTPUT

    - name: Commit
      uses: Gottox/irc-message-action@v2.1.5
      if: github.event_name == 'push'
      with:
        channel: '#aircrack-ng'
        nickname: ${{steps.random.outputs.username}}
        message: |-
          Commit by ${{ github.actor }}: ${{ github.event.compare }}
          ${{ join(github.event.commits.*.message) }}

    - name: Pull Request Created
      uses: Gottox/irc-message-action@v2.1.5
      if: github.event_name == 'pull_request'
      with:
        channel: '#aircrack-ng'
        nickname: ${{steps.random.outputs.username}}
        message: |-
          New pull request #${{ github.event.number }} by ${{ github.actor }}: ${{ github.event.pull_request.title }} - ${{ github.event.pull_request.html_url }}

    - name: Issue created
      uses: Gottox/irc-message-action@v2.1.5
      if: github.event_name == 'issues' && github.event.action == 'opened' && github.event.issue.draft == false
      with:
        channel: '#aircrack-ng'
        nickname: ${{steps.random.outputs.username}}
        message: |-
          New issue #${{github.event.issue.number}} (${{github.event.issue.url}}) by ${{ github.actor }}: ${{github.event.issue.title}} ()

    - name: New tag/release
      uses: Gottox/irc-message-action@v2.1.5
      if: github.event_name == 'create' && github.event.ref_type == 'tag'
      with:
        channel: '#aircrack-ng'
        nickname: ${{steps.random.outputs.username}}
        message: |-
          New release in GitHub: ${{ github.event.ref }}