name: Linux PCRE CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches: [ master ]
    paths-ignore:
      - apparmor/**
      - contrib/**
      - manpages/**
      - patches/**
      - test/**
      - '.coverityignore'
      - '.github/workflows/gentoo.yml'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/almalinux.yml'
      - '.github/workflows/alpine.yml'
      - '.github/workflows/check-actions-updates.yml'
      - '.github/workflows/check-release-ready.yml'
      - '.github/workflows/codespell.yml'
      - '.github/workflows/coverity.yml'
      - '.github/workflows/devcontainer.yml'
      - '.github/workflows/docker.yml'
      - '.github/workflows/docker-release.yml'
      - '.github/workflows/dragonflybsd.yml'
      - '.github/workflows/freebsd.yml'
      - '.github/workflows/gcc.yml'
      - '.github/workflows/irc.yml'
      - '.github/workflows/kali.yml'
      - '.github/workflows/linux.yml'
      - '.github/workflows/macos.yml'
      - '.github/workflows/manual.yml'
      - '.github/workflows/markdown-link.yml'
      - '.github/workflows/netbsd.yml'
      - '.github/workflows/openbsd.yml'
      - '.github/workflows/pvs-studio.yml'
      - '.github/workflows/scanbuild.yml'
      - '.github/workflows/style.yml'
      - '.github/workflows/windows.yml'
      - '.vscode/**'
      - '.devcontainer/**'
      - '.clang-format'
      - '.codespellrc'
      - '.editorconfig'
      - '.gitignore'
      - '.pre-commit-config.yaml'
      - 'AC_VERSION.in'
      - 'AUTHORS'
      - 'centos_autotools.sh'
      - 'ChangeLog'
      - 'docker_package_install.sh'
      - 'Dockerfile'
      - 'Dockerfile.release'
      - 'INSTALLING'
      - 'LICENSE'
      - 'LICENSE.OpenSSL'
      - 'README'
      - 'README.md'
      - 'SECURITY.md'
      - 'scripts/airmon-ng.*'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - apparmor/**
      - contrib/**
      - manpages/**
      - patches/**
      - test/**
      - '.coverityignore'
      - '.github/workflows/gentoo.yml'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/almalinux.yml'
      - '.github/workflows/alpine.yml'
      - '.github/workflows/check-actions-updates.yml'
      - '.github/workflows/check-release-ready.yml'
      - '.github/workflows/codespell.yml'
      - '.github/workflows/coverity.yml'
      - '.github/workflows/devcontainer.yml'
      - '.github/workflows/docker.yml'
      - '.github/workflows/docker-release.yml'
      - '.github/workflows/dragonflybsd.yml'
      - '.github/workflows/freebsd.yml'
      - '.github/workflows/gcc.yml'
      - '.github/workflows/irc.yml'
      - '.github/workflows/kali.yml'
      - '.github/workflows/linux.yml'
      - '.github/workflows/macos.yml'
      - '.github/workflows/manual.yml'
      - '.github/workflows/markdown-link.yml'
      - '.github/workflows/netbsd.yml'
      - '.github/workflows/openbsd.yml'
      - '.github/workflows/pvs-studio.yml'
      - '.github/workflows/scanbuild.yml'
      - '.github/workflows/style.yml'
      - '.github/workflows/windows.yml'
      - '.vscode/**'
      - '.devcontainer/**'
      - '.clang-format'
      - '.codespellrc'
      - '.editorconfig'
      - '.gitignore'
      - '.pre-commit-config.yaml'
      - 'AC_VERSION.in'
      - 'AUTHORS'
      - 'centos_autotools.sh'
      - 'ChangeLog'
      - 'docker_package_install.sh'
      - 'Dockerfile'
      - 'Dockerfile.release'
      - 'INSTALLING'
      - 'LICENSE'
      - 'LICENSE.OpenSSL'
      - 'README'
      - 'README.md'
      - 'SECURITY.md'
      - 'scripts/airmon-ng.*'

env:
  LANG: en_US.UTF-8
  TZ: UTC

jobs:
  ubuntu_22_04:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - cc:  gcc
            cxx: g++
          - cc:  clang
            cxx: clang++
        flags:
          - name: OpenSSL
            flags: ""

    name: Ubuntu 22.04 ${{ matrix.compiler.cc }} using ${{ matrix.flags.name }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 750
          submodules: 'recursive'

      - uses: actions/cache@v4
        id: cache
        if: ${{ env.ACT != 'true' }}
        with:
          path: |
            /home/runner/.ccache
          key: ${{ runner.os }}-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}-${{ hashFiles('.github/workflows/linux-pcre.yml') }}
          restore-keys: ${{ runner.os }}-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}

      - name: Install dependencies
        run: |
          SUDO="$([ "$ACT" = "true" ] || echo sudo)"
          $SUDO apt update -q
          $SUDO apt-get install -y git autoconf automake build-essential ccache ethtool expect hostapd iw lcov libcmocka-dev libhwloc-dev libnl-3-dev libnl-genl-3-dev libpcap-dev libpcre3-dev libsqlite3-dev libssl-dev libtool pkg-config rfkill screen shtool tcpdump usbutils wpasupplicant zlib1g-dev

      - name: Ccache stats before builds
        run: |
          ccache -s

      - name: Build with ${{ matrix.compiler.cc }} using ${{ matrix.flags.name }}
        env:
          AM_COLOR_TESTS: always
        run: |
          CPUS=$(nproc)
          case "${{ matrix.compiler.cc }}" in
            clang)
              CC=clang
              CXX=clang++
              export CFLAGS="-Werror -Wno-zero-length-array -Wno-deprecated-declarations"
              export CXXFLAGS="-Werror -Wno-zero-length-array -Wno-deprecated-declarations"
              ;;
            *)
              CC=${{ matrix.compiler.cc }}
              CXX=${{ matrix.compiler.cxx }}
              export CFLAGS="-Werror -Wno-unused-result -Wno-deprecated-declarations"
              export CXXFLAGS="-Werror -Wno-unused-result -Wno-deprecated-declarations"
              ;;
          esac
          export CC="ccache $CC"
          export CXX="ccache $CXX"
          echo "::group::make distclean"
          make distclean || :
          echo "::endgroup::"
          echo "::group::autoreconf"
          autoreconf -vif
          echo "::endgroup::"
          echo "::group::configure"
          mkdir linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}
          cd linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}
          echo ">> Configure with $CC, $CXX, and ${{ matrix.flags.flags }}"
          ../configure --without-opt --with-experimental --enable-maintainer-mode ${{ matrix.flags.flags }} || { cat config.log; exit 1; }
          echo "::endgroup::"
          echo "::group::build"
          echo ">> Build using ${CPUS} jobs"
          make -j ${CPUS}
          echo "::endgroup::"
          cd ..

      - name: Ccache stats after builds
        run: |
          ccache -s

  ubuntu_20_04:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - cc:  gcc
            cxx: g++
          - cc:  clang
            cxx: clang++
        flags:
          - name: OpenSSL
            flags: ""

    name: Ubuntu 20.04 ${{ matrix.compiler.cc }} using ${{ matrix.flags.name }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 750
          submodules: 'recursive'

      - uses: actions/cache@v4
        id: cache
        if: ${{ env.ACT != 'true' }}
        with:
          path: |
            /home/runner/.ccache
          key: ${{ runner.os }}-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}-${{ hashFiles('.github/workflows/linux-pcre.yml') }}
          restore-keys: ${{ runner.os }}-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}

      - name: Install dependencies
        run: |
          sudo apt update -q
          sudo apt-get install -y autoconf automake build-essential ccache ethtool expect hostapd iw lcov libcmocka-dev libhwloc-dev libnl-3-dev libnl-genl-3-dev libpcap-dev libpcre3-dev libsqlite3-dev libssl-dev libtool pkg-config rfkill screen shtool tcpdump usbutils wpasupplicant zlib1g-dev

      - name: Ccache stats before builds
        run: |
          ccache -s

      - name: Build with ${{ matrix.compiler.cc }} using ${{ matrix.flags.name }}
        env:
          AM_COLOR_TESTS: always
        run: |
          CPUS=$(nproc)
          export CC="ccache ${{ matrix.compiler.cc }}"
          export CXX="ccache ${{ matrix.compiler.cxx }}"
          echo "::group::make distclean"
          make distclean || :
          echo "::endgroup::"
          echo "::group::autoreconf"
          autoreconf -vif
          echo "::endgroup::"
          echo "::group::configure"
          mkdir linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}
          cd linux-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}
          echo ">> Configure with $CC, $CXX, and ${{ matrix.flags.flags }}"
          ../configure --without-opt --with-experimental --enable-maintainer-mode ${{ matrix.flags.flags }} || { cat config.log; exit 1; }
          echo "::endgroup::"
          echo "::group::build"
          echo ">> Build using ${CPUS} jobs"
          make -j ${CPUS}
          echo "::endgroup::"
          cd ..

      - name: Ccache stats after builds
        run: |
          ccache -s
