name: macOS CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches: [ master ]
    paths-ignore:
      - apparmor/**
      - contrib/**
      - manpages/**
      - patches/**
      - '.coverityignore'
      - '.github/workflows/gentoo.yml'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/almalinux.yml'
      - '.github/workflows/alpine.yml'
      - '.github/workflows/check-actions-updates.yml'
      - '.github/workflows/check-release-ready.yml'
      - '.github/workflows/codespell.yml'
      - '.github/workflows/coverity.yml'
      - '.github/workflows/devcontainer.yml'
      - '.github/workflows/docker.yml'
      - '.github/workflows/docker-release.yml'
      - '.github/workflows/dragonflybsd.yml'
      - '.github/workflows/freebsd.yml'
      - '.github/workflows/gcc.yml'
      - '.github/workflows/irc.yml'
      - '.github/workflows/kali.yml'
      - '.github/workflows/linux-pcre.yml'
      - '.github/workflows/linux.yml'
      - '.github/workflows/manual.yml'
      - '.github/workflows/markdown-link.yml'
      - '.github/workflows/netbsd.yml'
      - '.github/workflows/openbsd.yml'
      - '.github/workflows/pvs-studio.yml'
      - '.github/workflows/scanbuild.yml'
      - '.github/workflows/style.yml'
      - '.github/workflows/windows.yml'
      - '.vscode/**'
      - '.devcontainer/**'
      - '.clang-format'
      - '.codespellrc'
      - '.editorconfig'
      - '.gitignore'
      - '.pre-commit-config.yaml'
      - 'AC_VERSION.in'
      - 'AUTHORS'
      - 'centos_autotools.sh'
      - 'ChangeLog'
      - 'docker_package_install.sh'
      - 'Dockerfile'
      - 'Dockerfile.release'
      - 'INSTALLING'
      - 'LICENSE'
      - 'LICENSE.OpenSSL'
      - 'README'
      - 'README.md'
      - 'SECURITY.md'
      - 'scripts/airmon-ng.*'

  pull_request:
    branches: [ master ]
    paths-ignore:
      - apparmor/**
      - contrib/**
      - manpages/**
      - patches/**
      - '.coverityignore'
      - '.github/workflows/gentoo.yml'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/almalinux.yml'
      - '.github/workflows/alpine.yml'
      - '.github/workflows/check-actions-updates.yml'
      - '.github/workflows/check-release-ready.yml'
      - '.github/workflows/codespell.yml'
      - '.github/workflows/coverity.yml'
      - '.github/workflows/devcontainer.yml'
      - '.github/workflows/docker.yml'
      - '.github/workflows/docker-release.yml'
      - '.github/workflows/dragonflybsd.yml'
      - '.github/workflows/freebsd.yml'
      - '.github/workflows/gcc.yml'
      - '.github/workflows/irc.yml'
      - '.github/workflows/kali.yml'
      - '.github/workflows/linux-pcre.yml'
      - '.github/workflows/linux.yml'
      - '.github/workflows/manual.yml'
      - '.github/workflows/markdown-link.yml'
      - '.github/workflows/netbsd.yml'
      - '.github/workflows/openbsd.yml'
      - '.github/workflows/pvs-studio.yml'
      - '.github/workflows/scanbuild.yml'
      - '.github/workflows/style.yml'
      - '.github/workflows/windows.yml'
      - '.vscode/**'
      - '.devcontainer/**'
      - '.clang-format'
      - '.codespellrc'
      - '.editorconfig'
      - '.gitignore'
      - '.pre-commit-config.yaml'
      - 'AC_VERSION.in'
      - 'AUTHORS'
      - 'centos_autotools.sh'
      - 'ChangeLog'
      - 'docker_package_install.sh'
      - 'Dockerfile'
      - 'Dockerfile.release'
      - 'INSTALLING'
      - 'LICENSE'
      - 'LICENSE.OpenSSL'
      - 'README'
      - 'README.md'
      - 'SECURITY.md'
      - 'scripts/airmon-ng.*'

env:
  LANG: en_US.UTF-8
  TZ: UTC

jobs:
  macos:
    runs-on: macos-13

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - cc:  gcc
            cxx: g++
          - cc:  clang
            cxx: clang++
        flags:
          - name: Gcrypt
            flags: "--with-gcrypt"
          - name: OpenSSL
            flags: ""

    name: macOS ${{ matrix.compiler.cc }} using ${{ matrix.flags.name }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 750
          submodules: 'recursive'

      - uses: actions/cache@v4
        id: cache
        with:
          path: |
            /Users/runner/Library/Caches/ccache
            /Users/runner/Library/Preferences/ccache/ccache.conf
          key: ${{ runner.os }}-macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}-${{ hashFiles('.github/workflows/macos.yml') }}
          restore-keys: ${{ runner.os }}-macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}

      - name: Install dependencies
        run: |
          brew install autoconf automake ccache cmocka expect hwloc libpcap libtool openssl pcre2 pkg-config sqlite3 shtool md5sha1sum

      - name: Ccache stats before builds
        run: |
          ccache -s

      - name: Build with ${{ matrix.compiler.cc }} using ${{ matrix.flags.name }}
        env:
          AM_COLOR_TESTS: always
        run: |
          CPUS=$(($(sysctl -a | grep machdep.cpu.cores_per_package | awk '{ print $2 }') * 3 / 2))
          export PATH="/usr/local/opt/ccache/libexec:$PATH"
          case "${{ matrix.compiler.cc }}" in
            clang)
              CC=clang
              CXX=clang++
              export CFLAGS="-Werror -Wno-zero-length-array -Wno-deprecated-declarations"
              export CXXFLAGS="-Werror -Wno-zero-length-array -Wno-deprecated-declarations"
              ;;
            *)
              CC=${{ matrix.compiler.cc }}
              CXX=${{ matrix.compiler.cxx }}
              export CFLAGS="-Werror -Wno-unused-result -Wno-deprecated-declarations"
              export CXXFLAGS="-Werror -Wno-unused-result -Wno-deprecated-declarations"
              ;;
          esac
          export CC="ccache $CC"
          export CXX="ccache $CXX"
          echo "::group::make distclean"
          make distclean || :
          echo "::endgroup::"
          echo "::group::autoreconf"
          autoreconf -vif
          echo "::endgroup::"
          echo "::group::configure"
          mkdir macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}
          cd macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}
          echo ">> Configure with $CC, $CXX, and ${{ matrix.flags.flags }}"
          ../configure --without-opt --with-experimental --enable-maintainer-mode ${{ matrix.flags.flags }} || { cat config.log; exit 1; }
          echo "::endgroup::"
          echo "::group::build"
          echo ">> Build using ${CPUS} jobs"
          make -j ${CPUS}
          echo "::endgroup::"
          echo "::group::run tests"
          make -j ${CPUS} check || { find . -name 'test-suite.log' -exec cat {} ';' && exit 1; }
          echo "::endgroup::"
          cd ..

      - name: Ccache stats after builds
        run: |
          ccache -s

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}
          path: |
            macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}
            !macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/.deps
            !macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/.dirstamp
            !macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/*.a
            !macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/*.la
            !macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/*.lai
            !macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/*.o
            !macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/*.lo

  macos-arm64:
    runs-on: macos-14

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - cc:  gcc
            cxx: g++
          - cc:  clang
            cxx: clang++
        flags:
          - name: Gcrypt
            flags: "--with-gcrypt"
          - name: OpenSSL
            flags: ""

    name: macOS ARM64 ${{ matrix.compiler.cc }} using ${{ matrix.flags.name }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 750
          submodules: 'recursive'

      - uses: actions/cache@v4
        id: cache
        with:
          path: |
            /Users/runner/Library/Caches/ccache
            /Users/runner/Library/Preferences/ccache/ccache.conf
          key: ${{ runner.os }}-macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}-${{ hashFiles('.github/workflows/macos.yml') }}
          restore-keys: ${{ runner.os }}-macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}

      - name: Install dependencies
        run: |
          brew install autoconf automake ccache cmocka expect hwloc libpcap libtool openssl pcre2 pkg-config sqlite3 shtool md5sha1sum

      - name: Ccache stats before builds
        run: |
          ccache -s

      - name: Build with ${{ matrix.compiler.cc }} using ${{ matrix.flags.name }}
        env:
          AM_COLOR_TESTS: always
        run: |
          CPUS=$(($(sysctl -a | grep machdep.cpu.cores_per_package | awk '{ print $2 }') * 3 / 2))
          export PATH="/usr/local/opt/ccache/libexec:$PATH"
          case "${{ matrix.compiler.cc }}" in
            clang)
              CC=clang
              CXX=clang++
              export CFLAGS="-Werror -Wno-zero-length-array -Wno-deprecated-declarations"
              export CXXFLAGS="-Werror -Wno-zero-length-array -Wno-deprecated-declarations"
              ;;
            *)
              CC=${{ matrix.compiler.cc }}
              CXX=${{ matrix.compiler.cxx }}
              export CFLAGS="-Werror -Wno-unused-result -Wno-deprecated-declarations"
              export CXXFLAGS="-Werror -Wno-unused-result -Wno-deprecated-declarations"
              ;;
          esac
          export CC="ccache $CC"
          export CXX="ccache $CXX"
          echo "::group::make distclean"
          make distclean || :
          echo "::endgroup::"
          echo "::group::autoreconf"
          autoreconf -vif
          echo "::endgroup::"
          echo "::group::configure"
          mkdir macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}
          cd macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}
          echo ">> Configure with $CC, $CXX, and ${{ matrix.flags.flags }}"
          ../configure --without-opt --with-experimental --enable-maintainer-mode ${{ matrix.flags.flags }} || { cat config.log; exit 1; }
          echo "::endgroup::"
          echo "::group::build"
          echo ">> Build using ${CPUS} jobs"
          make -j ${CPUS}
          echo "::endgroup::"
          echo "::group::run tests"
          make -j ${CPUS} check || { find . -name 'test-suite.log' -exec cat {} ';' && exit 1; }
          echo "::endgroup::"
          cd ..

      - name: Ccache stats after builds
        run: |
          ccache -s

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}
          path: |
            macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}
            !macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/.deps
            !macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/.dirstamp
            !macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/*.a
            !macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/*.la
            !macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/*.lai
            !macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/*.o
            !macos-${{ matrix.compiler.cc }}-${{ matrix.flags.name }}/**/*.lo
